# Include arguments 
set( CMAKE_INCLUDE_FLAG_WLA_Z80 "-I" )       

# How to build objects 
set( CMAKE_WLA_Z80_COMPILE_OBJECT
    "<CMAKE_WLA_Z80_COMPILER> <FLAGS> <INCLUDES> -o <OBJECT> <SOURCE>"
)

# How to build objects 
set( CMAKE_WLA_Z80_CREATE_STATIC_LIBRARY
    "wlalink <LINK_FLAGS> -o <TARGET>"
)

# How to build executables 
set( CMAKE_WLA_Z80_LINK_EXECUTABLE 
    "wlalink <LINK_FLAGS> <TARGET>"
)


set( CMAKE_Gambit_INFORMATION_LOADED 1 )


# CMAKE_(LANG)_CREATE_SHARED_LIBRARY
# CMAKE_(LANG)_CREATE_SHARED_MODULE
# CMAKE_(LANG)_CREATE_STATIC_LIBRARY
# CMAKE_(LANG)_COMPILE_OBJECT
# CMAKE_(LANG)_LINK_EXECUTABLE